### ISSUE TITLE
请问该项目中几个参考文献风格各有什么作用

### ISSUE THREAD

**Issue by cddwx525** [tuxify/zzuthesis#1]
该项目根目录里有三个参考文献风格：

1. gbt-7714-2015-numerical.bst
2. gbt-7714-2015-author-year.bst
3. zzubib.bst

从字面意思看，前两个是 gbt-7714-2015 标准风格，只是排序不同，后面是郑州大学风格，但是 main.tex 里用了 gbt-7714-2015-numerical 这个，按意思不是应该用 zzubib.bst 吗。

**Comment by tuxify** [comment]
> 该项目根目录里有三个参考文献风格：
> 
> 1. gbt-7714-2015-numerical.bst
> 2. gbt-7714-2015-author-year.bst
> 3. zzubib.bst
> 
> 从字面意思看，前两个是 gbt-7714-2015 标准风格，只是排序不同，后面是郑州大学风格，但是 main.tex 里用了 gbt-7714-2015-numerical 这个，按意思不是应该用 zzubib.bst 吗。

现在应该直接用 gbt-7714-2015-numerical.bst 就好了，如果跟学校标准有不一致的可以反馈。zzubib.bst 采用的是当时的国家标准 GB/T 7714-2005，国标更新为 GB/T 7714-2015 后，已经有很好的宏包来实现这个标准了（即 [gbt7714](https://ctan.org/pkg/gbt7714)），就没再更新 zzubib.bst 这个文件了，因为也没对 gbt7714 这个包做任何修改，也就没改名字，直接用原名了。
