### ISSUE TITLE
参考文献风格 gbt-7714-2015-numerical 与校方规范出入之处

### ISSUE THREAD

**Issue by cddwx525** [tuxify/zzuthesis#2]
使用 gbt-7714-2015-numerical 参考文献风格的编译结果与校方规范（郑州大学博士硕士学位论文写作规范，郑州大学学位办公室 2009 年 10 月，以下简称规范）文件中的例子对比如下图所示（左侧是规范例子，右侧是编译输出）：

![zzu_vs_gbt](https://user-images.githubusercontent.com/8937441/67624314-a6796300-f861-11e9-90a9-58742ad9a72f.png)

其实规范中的格式描述和例子也有矛盾的地方，这里以例子为准进行对比，而且不考虑有些全半角符号的问题，gbt-7714-2015-numerical 风格应主要调整的地方如下：

- 作者的姓应只大写首字母
- 末尾点号应省略
- 页码连接符应是波浪线
- 不要 doi, url,
- 不要 OL 标识
- 学位论文。标识之后应加上相应内容（参照对比图）
- 专著。翻译者和“译”之间应不要逗号
- 专著。版本号之前应加上"第"字
- 专著。文献类型标识应在版本号之后
- 专著。出版年和页码之间应是点号
- 论文集。应按照”见（in）：编者，编（eds）.文集名“的格式
- 论文集。出版年和页码之间应是点号
- 专利。应显示“中国专利”字样
- 专利。应显示专利号
- 专利。应使用相应日期格式（参照对比图）
- 电子文献。应使用EB标识

使用模板版本： [Sat Jan 20 01:29:17 2018 +0800](https://github.com/tuxify/zzuthesis/tree/4ce94f80d8582827682c4761115d469ff9ded1cd)

所用的 bib 文件：

```bibtex
@Article{陈建军2001,
  author  = {陈建军 and 车建文 and 陈勇},
  title   = {具有频率和振型概率约束的工程结构动力优化设计},
  journal = {计算力学学报},
  year    = {2001},
  volume  = {18},
  number  = {1},
  pages   = {74--80},
  groups  = {2019-10-26_bsttest},
}

@Article{NADKARNI1992,
  author    = {NADKARNI, M. A. and Nair, C. K. K. and Pandey, V. N. and Pradhan, D. S.},
  title     = {Characterization of alpha-galactosidase from corynebacterium murisepticum and mechanism of its induction},
  journal   = {The Journal of General and Applied Microbiology},
  year      = {1992},
  volume    = {38},
  pages     = {23--34},
  groups    = {2019-10-26_bsttest},
  publisher = {Applied Microbiology, Molecular and Cellular Biosciences Research Foundation},
}

@Article{华罗庚1973,
  author  = {华罗庚 and 王元},
  title   = {论一致分布与近似分析：数论方法（\uppercase\expandafter{\romannumeral1}）},
  journal = {中国科学},
  year    = {1973},
  number  = {4},
  pages   = {339--357},
  groups  = {2019-10-26_bsttest},
}

@Inbook{竺可桢1973,
  pages     = {104--107},
  title     = {物候学},
  publisher = {科学出版社},
  year      = {1973},
  author    = {竺可桢},
  address   = {北京},
  groups    = {2019-10-26_bsttest},
}

@Inbook{霍夫斯塔1981,
  pages      = {798--799},
  title      = {禽病学：下册},
  publisher  = {农业出版社},
  year       = {1981},
  author     = {霍夫斯塔},
  address    = {北京},
  edition    = {7},
  translator = {胡祥壁},
  groups     = {2019-10-26_bsttest},
}

@Inbook{Timoshenko1959,
  pages     = {17--36},
  title     = {Theory of plate and shells},
  publisher = {McGraw-Hil1},
  year      = {1959},
  author    = {Timoshenko, S. P.},
  address   = {New York},
  edition   = {2},
  groups    = {2019-10-26_bsttest},
}

@Collection{张全福1991,
  author    = {张全福 and 王里青},
  title     = {“百家争鸣”与理工科学报编辑工作},
  editor    = {郑福寿},
  maintitle = {学报编辑论丛：第 2 集},
  year      = {1991},
  address   = {南京},
  publisher = {河海大学出版社},
  pages     = {1--4},
  groups    = {2019-10-26_bsttest},
}

@InProceedings{Dupont1974,
  author    = {Dupont, B.},
  title     = {Bone marrow transplantation in severe combined immunodeficiency with an unrclated {MLC} compatible donor},
  booktitle = {Proceedings of the Third Annual Meeting of the International Society for Experimental Hematology},
  year      = {1974},
  editor    = {White, H. J，and Smith, R.},
  pages     = {44--46},
  address   = {Houston},
  publisher = {International Society for Experimental Hematology},
  groups    = {2019-10-26_bsttest},
}

@PhdThesis{丁光莹2001,
  author  = {丁光莹},
  title   = {钢筋混凝土框架结构非线性反应分析的随机模拟分析},
  school  = {同济大学},
  year    = {2001},
  address = {上海},
  groups  = {2019-10-26_bsttest},
}

@PhdThesis{Cairns1965,
  author  = {Cairns, R. B.},
  title   = {Infrared spectroscopic studies on solid oxygen},
  school  = {Univ of California},
  year    = {1965},
  address = {Berkeley},
  groups  = {2019-10-26_bsttest},
}

@Patent{姜锡洲1989,
  nationality = {中国专利},
  number      = {881056073},
  year        = {1989},
  author      = {姜锡洲},
  title       = {一种温热外敷药制备方法},
  day         = {26},
  month       = jul,
  groups      = {2019-10-26_bsttest},
}

@Standard{全国文献工作标准化技术委员会第六分委员会1986,
  title        = {{GB 6447—86} 文摘编写规则},
  organization = {全国文献工作标准化技术委员会第六分委员会},
  author       = {全国文献工作标准化技术委员会第六分委员会},
  address      = {北京},
  year         = {1986},
  publisher    = {中国标准出版社},
  groups       = {2019-10-26_bsttest},
}

@Misc{王文惠2005,
  author = {王文惠 and 孟兵},
  title  = {利用不变量进行基于内容的图像检索},
  year   = {2005},
  groups = {2019-10-26_bsttest},
  url    = {http://www.image2003.com/paper/down/2005528115935222.pdf},
}
```

**Comment by cddwx525** [comment]
我通过查资料知道本项目中的 [gbt-7714-2015-numerical.bst](https://github.com/CTeX-org/gbt7714-bibtex-style/tree/d2b0d80072934ba27dd350f0974fe3d8af5db38e) 文件是很早的版本了，现在它的作者已经做了很多改进，或许我可以先到那里看看。

**Comment by tuxify** [comment]
我查了学校的规范，其中提到建议根据《中国高校自然科学学报编排规范》的要求书写参考文献，并按顺序编码制，而《中国高校自然科学学报编排规范》中规定参考文献的著录应执行 GB 7714-87 的规定。标准 GB 7714-87 目前来说太陈旧了，后面经过了两次修改，现在最新的标准是 GB/T 7714-2015，按照 GB/T 7714-2015 的规定，其应该是取代 2005 年和 1987 年的标准的，我不确定是否必须按 1987 年的标准执行。

我没有对所有的细节进行核对，就作者的姓来说，2015 年和 2005 年的规定中均为大写，而 1987 年的标准则为仅首字母大写。gbt-7714-2015-numerical.bst 这个风格实际上是符合 2015 年新国标的规定的，即使后续有更新，也应该会保持这个风格。学校规范中给出的例子应该是按照 1987 年标准中的规定给出的。

我不太确定现在学校对于这一方面的要求是否很苛刻，如果可以按 2015 年的标准，则可以把项目中的  gbt-7714-2015-numerical.bst 文件替换为最新版本，如果必须按 1987 年的标准，则可能需要自定义 bst 文件。

**Comment by cddwx525** [comment]
@tuxify 
没错，《中国高校自然科学学报编排规范》（1998年那个，应该是最新的吧）规定了参考文献的著录应执行 GB 7714-87 的规定，我之前下载了这个规范但是没仔细看它引用的哪个标准，现在知道了，这就难怪用 gbt-7714-2015 时与例子差这么多。

gbt-7714-2015-numerical.bst 新版的增加了一些开关配置项，方便用户自定义，不过默认配置下编译结果除了专利这个条目有点差别外其他都与本项目中的一致。

我刚注意到有的优秀论文（2016年）也会多少会出现与学校规范不一致的情况，所以学校对这方面的要求应该没那么严格吧。这样看的话，现在用这个 2015 标准风格应该也没啥问题，不过版本倒是可以考虑更新一下。如果学校有特殊要求或者出现哪个强迫症用户的话再说:-P，感谢作者的付出。

**Comment by tuxify** [comment]
@cddwx 在 gbt7714-unsrt.bst (版本：2019/03/21 v1.1.1) 的基础上修改了一个 zzubib.bst，基本可以符合学校的示例。不过没有进行仔细的测试，而且部分解决方案比较粗暴，没有通用性，建议如果不是学校特别要求的话，采用符合最新版国标的文献风格（gbt7714-unsrt.bst）即可。

TeXLive 发行版已经包含了 gbt7714-unsrt.bst 文件，因此直接在 main.tex 中调用即可，项目中删除了其他 bst 文件。

**Comment by cddwx525** [comment]
没想到你还是修改了，赞！试了试确实是基本符合了，然而某些地方是你在 bib 文件上做了微调，如果条件允许的话希望以后可以逐步改进。
