### ISSUE TITLE
OT和仿宋字体错误

### ISSUE THREAD

**Issue by a5corpii** [tuxify/zzuthesis#5]
我现在用的是 Manjaro + TeX Live 2019

可以生成pdf，但是会有报错，最先出现的应该是这个：
```
kpathsea: Running mktexmf OT
! I can't find file `OT'.
<*> \mode:=ljfour; mag:=1; nonstopmode; input OT
```
还有仿宋的问题：
```
Package fontspec Warning: Font "FangSong" does not contain requested Script
(fontspec)                "CJK".
```

相关的内容会显示不出来。

请问您是怎样设置字体的？我除了 ttf-wps-fonts 和 ttf-ms-fonts 没有安装其他额外的字体。当然TeX自带的那一堆是有的。

谢谢！

**Comment by tuxify** [comment]
@HesperusArcher
本科毕业设计论文封面（即“郑州大学毕业设计 (论文)”字样）用到加粗仿宋字体，模板中采用了伪粗体来实现。在定义支持伪粗体仿宋字体的命令时，指定了字体为 FangSong，因此导致只能在系统安装了 simfang.ttf 字体的前提下才能编译成功。现将所需加粗文字单独生成 pdf 文件（zzubachelor.pdf），以图片形式插入文档，无需额外安装该字体即可编译。
之前硕博论文模板中用到行楷字体（封面中“郑州大学”字样），也是直接生成了所需字体的文件（zzu.pdf），无需额外安装该字体。
如需对上述“郑州大学毕业设计 (论文)”和“郑州大学”的显示格式进行调整，则需安装相应字体后，对 figure 文件下 zzubachelor.tex 和 zzu.tex 文件进行修改即可。
目前，模板中所有字体均采用 ctex 宏包中的设置，可参考该文档查看具体字体配置。
