### ISSUE TITLE
请增加对「综述」的支持

### ISSUE THREAD

**Issue by a5corpii** [tuxify/zzuthesis#6]
医学类，要求有「综述」。

位于正文的参考文献后、个人简历前。

大概格式为：
```latex
\leftline{综述} %格式与一级标题一致
\centerline{\题目}
\centerline{综述 \姓名  \hspace{}  审校 \导师}
XXXX
\section
XXXX
\section
XXXX
```

综述及下属各section在contents里，均不编号。

我尝试在.cls文件里定义，未成功，求助。

**Comment by a5corpii** [comment]
综述部分需要独立的参考文献。

「综述」在页眉居中，文中居左，在.cls中一直没有实现。

谢谢！

**Comment by tuxify** [comment]
@HesperusArcher

已增加 review 环境提供该功能，同时提供了一个示例，为不影响其他人使用，该部分在 main 文件中是注释掉的，取消注释即可。

目前附录中的参考文献均为手动输入的，如果需要自动生成，可考虑采用 multibib 宏包。

**Comment by a5corpii** [comment]
Thx, 参考文献我已使用`biblatex`解决，但是与`natbib`冲突。

我们这边的要求，review是一个单独的文章，故不使用全文的title。英文缩略词表的格式也不相同。

我过几天整理一下，看能不能提个PR。
