### ISSUE TITLE
make: *** No rule to make target 'zzuthesis.cfg', needed by 'main.pdf'

### ISSUE THREAD

**Issue by xuefengze** [tuxify/zzuthesis#8]
使用`make thesis`会报错，`No rule to make target 'zzuthesis.cfg', needed by 'main.pdf'`，缺少`zzuthesis.cfg`，我是第一次用，对这不是很了解。使用的系统：`WSL2: Ubuntu-20.04`，`TeXLive 2019`。

**Comment by tuxify** [comment]
> 

删除 `Makefile` 中的 `$(PACKAGE).cfg` 即可。
原来配置文件部分是分成两个文件的，后来合并为一个之后，忘记删除 `Makefile` 中的了。
